name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build Application
        run: mvn clean package -DskipTests

      - name: Verify Docker Secret
        run: |
          if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
            echo "DOCKER_PASSWORD is EMPTY"
            exit 1
          else
            echo "DOCKER_PASSWORD is available"
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/stockservice:${{ github.sha }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/stockservice:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/stockservice:latest

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/stockservice:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/stockservice:latest
