server:
  port: 9001


spring:
  application:
    name: sms-stock-service


  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver


  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}


  data:
    redis:
      cluster:
        nodes: ${REDIS_CLUSTER_NODES}
        max-redirects: 3



management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

  endpoint:
    health:
      show-details: always